* Features
** Redact urls
*** TODO Redact headers
We should ask about this
** DONE based on four (actually three) regexes
** hash based caching
** Clean Events
** Clean Object
** DONE Path Segments and Query Param
** Add GeoData
sus: Uses data from 2019, No rust impl. There's a c-library.
** IP-address removal
** DONE Is-Bot ;;



* Todo
** Deployment
See ports.
This is maybe where Many k8s resources-as-nix-happen
** TODO Probes
*** V- GOES IN README
There's several green threads by tokio running different bits
of the program. They should fail at the same time. Experimentation
with panic! in one service confirms that they do. They also block at the same time
when tested with loop{}.
*** DONE /health
*** TODO /ready
**** Currently only returnin 200 OK when `path_string.contains("is_alive")`
Is-alive and is-ready are the same thing IFF this is a stateless proxy without
sync deps.

** Metrics
pingora has built in prometheus

* Wut
We need to expose multiple ports. Nais doesn't support that. Add these manually to the pod spec??
